# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import storage_node_pb2 as storage__node__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in storage_node_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StorageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestUUID = channel.unary_unary(
                '/storage.StorageService/RequestUUID',
                request_serializer=storage__node__pb2.UUIDRequest.SerializeToString,
                response_deserializer=storage__node__pb2.UUIDResponse.FromString,
                _registered_method=True)
        self.ValidateUUID = channel.unary_unary(
                '/storage.StorageService/ValidateUUID',
                request_serializer=storage__node__pb2.UUIDValidation.SerializeToString,
                response_deserializer=storage__node__pb2.UUIDResponse.FromString,
                _registered_method=True)
        self.UploadFile = channel.stream_unary(
                '/storage.StorageService/UploadFile',
                request_serializer=storage__node__pb2.FileChunk.SerializeToString,
                response_deserializer=storage__node__pb2.FileResponse.FromString,
                _registered_method=True)
        self.RequestFile = channel.unary_stream(
                '/storage.StorageService/RequestFile',
                request_serializer=storage__node__pb2.FileRequest.SerializeToString,
                response_deserializer=storage__node__pb2.FileChunk.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/storage.StorageService/DeleteFile',
                request_serializer=storage__node__pb2.FileDelete.SerializeToString,
                response_deserializer=storage__node__pb2.FileResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.stream_stream(
                '/storage.StorageService/Heartbeat',
                request_serializer=storage__node__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=storage__node__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class StorageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestUUID(self, request, context):
        """UUID Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateUUID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFile(self, request_iterator, context):
        """File Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestUUID': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestUUID,
                    request_deserializer=storage__node__pb2.UUIDRequest.FromString,
                    response_serializer=storage__node__pb2.UUIDResponse.SerializeToString,
            ),
            'ValidateUUID': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateUUID,
                    request_deserializer=storage__node__pb2.UUIDValidation.FromString,
                    response_serializer=storage__node__pb2.UUIDResponse.SerializeToString,
            ),
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=storage__node__pb2.FileChunk.FromString,
                    response_serializer=storage__node__pb2.FileResponse.SerializeToString,
            ),
            'RequestFile': grpc.unary_stream_rpc_method_handler(
                    servicer.RequestFile,
                    request_deserializer=storage__node__pb2.FileRequest.FromString,
                    response_serializer=storage__node__pb2.FileChunk.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=storage__node__pb2.FileDelete.FromString,
                    response_serializer=storage__node__pb2.FileResponse.SerializeToString,
            ),
            'Heartbeat': grpc.stream_stream_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=storage__node__pb2.HeartbeatRequest.FromString,
                    response_serializer=storage__node__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'storage.StorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('storage.StorageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StorageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestUUID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/RequestUUID',
            storage__node__pb2.UUIDRequest.SerializeToString,
            storage__node__pb2.UUIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateUUID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/ValidateUUID',
            storage__node__pb2.UUIDValidation.SerializeToString,
            storage__node__pb2.UUIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/storage.StorageService/UploadFile',
            storage__node__pb2.FileChunk.SerializeToString,
            storage__node__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/storage.StorageService/RequestFile',
            storage__node__pb2.FileRequest.SerializeToString,
            storage__node__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storage.StorageService/DeleteFile',
            storage__node__pb2.FileDelete.SerializeToString,
            storage__node__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/storage.StorageService/Heartbeat',
            storage__node__pb2.HeartbeatRequest.SerializeToString,
            storage__node__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
